In [91]:
import pandas as pd

In [313]:
%matplotlib inline

In [314]:
path = 'snb-data-fdiaustabsa-de-all-20171215_0900.xlsx'

In [315]:
df = pd.read_excel(path, na_values='-')

In [316]:
df

,Sektoren,Industrie - Total,Industrie - Textilien und Bekleidung,Industrie - Chemie und Kunststoffe,Industrie - Metalle und Maschinen,"Industrie - Elektronik, Energie, Optik und Uhren",Industrie - Übrige Industrien und Bau,Dienste - Total,Dienste - Handel,Dienste - Finanz- und Holdinggesellschaften - Total,...,Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - Total.3,Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - davon Special Purpose Entities.3,Dienste - Banken.3,Dienste - Versicherungen.3,Dienste - Transporte und Kommunikation.3,Dienste - Übrige Dienste.3,Total.3,Total ohne ausländisch beherrschte Finanz- und Holdinggesellschaften.3,Pro memoria: Grundstücks- und Wohnungswesen.1,Pro memoria: Total inkl. Grundstücks- und Wohnungswesen.1
0,1998,6374.000000,285.500,3829.800000,819.500000,108.000000,1331.200000,10574.800000,369.000000,565.500000,...,3869.900000,NaN,-321.200000,8034.400000,859.300000,62.000000,27209.200000,23339.300000,NaN,27209.200000
1,1999,4606.000000,440.000,198.500000,650.800000,1111.100000,2205.600000,19229.100000,52.800000,3778.300000,...,11479.600000,NaN,6082.000000,9910.200000,3524.300000,4121.300000,49986.200000,38506.600000,NaN,49986.200000
2,2000,17634.500000,19.000,7680.300000,1271.600000,2062.000000,6601.600000,38377.800000,109.200000,1900.700000,...,257.600000,NaN,31059.100000,14041.600000,196.300000,2265.600000,75445.800000,75188.200000,NaN,75445.600000
3,2001,8012.800000,-224.900,2583.700000,1707.400000,2071.500000,1875.100000,13982.600000,890.900000,167.500000,...,1884.700000,NaN,-793.600000,7492.800000,1521.100000,1528.000000,30916.200000,29031.500000,NaN,30916.200000
4,2002,11437.200000,37.300,3444.000000,431.800000,232.800000,7291.300000,13146.400000,-90.200000,3710.700000,...,4535.600000,NaN,436.800000,-573.200000,-1382.800000,-1220.400000,12785.000000,8249.400000,NaN,12785.200000
5,2003,2180.900000,421.500,-225.300000,1327.800000,-80.300000,737.200000,3399.600000,39.800000,1261.700000,...,4696.200000,NaN,6176.100000,1414.200000,-539.700000,576.300000,20794.500000,16098.300000,0.000000,20794.800000
6,2004,11829.500000,791.400,7521.200000,2249.500000,-100.200000,1367.600000,-212.800000,599.700000,-4270.200000,...,2245.500000,NaN,3225.100000,3815.200000,-46.800000,725.500000,32666.000000,30420.500000,0.000000,32665.800000
7,2005,10192.900000,1430.300,6763.700000,-585.900000,194.600000,2390.200000,11789.300000,1687.600000,2208.900000,...,8449.900000,NaN,8382.700000,5893.400000,1316.600000,2140.100000,63650.500000,55200.600000,0.000000,63650.600000
8,2006,30913.100000,1838.700,9533.200000,7321.600000,1129.900000,11089.700000,31762.700000,1189.600000,16769.000000,...,5370.500000,NaN,21907.100000,8941.900000,1196.900000,439.500000,95070.800000,89700.300000,852.446017,95923.446017
9,2007,9862.100000,3592.000,165.100000,3751.000000,198.800000,2155.200000,36614.000000,-947.700000,17193.800000,...,11120.000000,NaN,12187.200000,-3444.400000,7531.000000,5386.700000,61242.300000,50122.300000,694.783785,61937.083785
10,2008,14370.800000,1034.000,5693.100000,698.200000,-264.900000,7210.400000,34235.500000,422.800000,3007.200000,...,5788.500000,NaN,1095.400000,-7993.700000,954.500000,-422.600000,49100.100000,43311.600000,-513.841126,48586.058874
11,2009,8.200000,-69.000,-3851.000000,1162.000000,1402.700000,1363.500000,8347.500000,8931.200000,-6058.100000,...,1127.200000,NaN,3309.600000,6373.700000,213.900000,2420.600000,28703.300000,27576.100000,-148.883489,28554.416511
12,2010,1400.500000,-3157.400,4462.700000,-1089.300000,2655.700000,-1471.200000,27383.900000,6145.700000,13240.200000,...,48092.100000,NaN,4535.100000,13306.000000,500.300000,1634.500000,89378.100000,41286.000000,502.494731,89880.594731
13,2011,-8520.400000,-4491.200,-4833.600000,-7439.400000,2689.100000,5554.700000,12726.200000,6461.600000,-3132.700000,...,-1215.600000,NaN,1405.200000,11700.500000,539.000000,1545.900000,42754.600000,43970.200000,358.635129,43113.235129
14,2012,9014.200000,1073.200,2199.300000,1274.300000,1699.900000,2767.600000,23174.300000,4831.100000,7520.600000,...,-7250.100000,NaN,5186.700000,4583.700000,1020.000000,1613.100000,40870.300000,48120.400000,459.623152,41329.923152
15,2013,-3108.700000,-968.300,-1846.100000,-782.200000,-971.200000,1459.100000,11597.500000,-1859.000000,2346.000000,...,-2768.600000,NaN,13320.300000,4691.200000,780.300000,160.200000,35752.400000,38521.000000,-30.452894,35721.947106
16,2014,-6511.977010,-541.700,-151.988984,1252.580805,1000.660196,-8071.529027,-27645.577394,-18808.447112,5073.646085,...,10268.099110,-710.189437,-7009.333644,6933.005977,-816.939544,-5517.403718,-165.353450,-10433.452561,215.881831,50.528381
17,2015,1856.290809,-454.900,3072.031875,-1717.272654,1986.051412,-1029.619825,48917.792593,7353.350341,38288.166363,...,39083.287300,12155.954798,-2416.525205,7078.124248,3139.989783,447.955928,90077.985633,50994.698332,280.149600,90358.135233
18,2016,20677.644098,91.114,1631.599559,1218.177608,10285.139794,7451.613137,-7684.543826,2410.418923,-22882.337389,...,2070.568894,9467.991291,2116.945718,20102.670359,508.517275,5320.476411,70658.685896,68588.117002,766.624563,71425.310459

In [317]:
df.set_index('Sektoren')

,Industrie - Total,Industrie - Textilien und Bekleidung,Industrie - Chemie und Kunststoffe,Industrie - Metalle und Maschinen,"Industrie - Elektronik, Energie, Optik und Uhren",Industrie - Übrige Industrien und Bau,Dienste - Total,Dienste - Handel,Dienste - Finanz- und Holdinggesellschaften - Total,Dienste - Finanz- und Holdinggesellschaften - schweizerisch beherrscht,...,Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - Total.3,Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - davon Special Purpose Entities.3,Dienste - Banken.3,Dienste - Versicherungen.3,Dienste - Transporte und Kommunikation.3,Dienste - Übrige Dienste.3,Total.3,Total ohne ausländisch beherrschte Finanz- und Holdinggesellschaften.3,Pro memoria: Grundstücks- und Wohnungswesen.1,Pro memoria: Total inkl. Grundstücks- und Wohnungswesen.1
Sektoren,,,,,,,,,,,,,,,,,,,,,
1998,6374.000000,285.500,3829.800000,819.500000,108.000000,1331.200000,10574.800000,369.000000,565.500000,1133.400000,...,3869.900000,NaN,-321.200000,8034.400000,859.300000,62.000000,27209.200000,23339.300000,NaN,27209.200000
1999,4606.000000,440.000,198.500000,650.800000,1111.100000,2205.600000,19229.100000,52.800000,3778.300000,150.300000,...,11479.600000,NaN,6082.000000,9910.200000,3524.300000,4121.300000,49986.200000,38506.600000,NaN,49986.200000
2000,17634.500000,19.000,7680.300000,1271.600000,2062.000000,6601.600000,38377.800000,109.200000,1900.700000,2002.900000,...,257.600000,NaN,31059.100000,14041.600000,196.300000,2265.600000,75445.800000,75188.200000,NaN,75445.600000
2001,8012.800000,-224.900,2583.700000,1707.400000,2071.500000,1875.100000,13982.600000,890.900000,167.500000,1394.800000,...,1884.700000,NaN,-793.600000,7492.800000,1521.100000,1528.000000,30916.200000,29031.500000,NaN,30916.200000
2002,11437.200000,37.300,3444.000000,431.800000,232.800000,7291.300000,13146.400000,-90.200000,3710.700000,2345.200000,...,4535.600000,NaN,436.800000,-573.200000,-1382.800000,-1220.400000,12785.000000,8249.400000,NaN,12785.200000
2003,2180.900000,421.500,-225.300000,1327.800000,-80.300000,737.200000,3399.600000,39.800000,1261.700000,785.600000,...,4696.200000,NaN,6176.100000,1414.200000,-539.700000,576.300000,20794.500000,16098.300000,0.000000,20794.800000
2004,11829.500000,791.400,7521.200000,2249.500000,-100.200000,1367.600000,-212.800000,599.700000,-4270.200000,-1476.000000,...,2245.500000,NaN,3225.100000,3815.200000,-46.800000,725.500000,32666.000000,30420.500000,0.000000,32665.800000
2005,10192.900000,1430.300,6763.700000,-585.900000,194.600000,2390.200000,11789.300000,1687.600000,2208.900000,-779.100000,...,8449.900000,NaN,8382.700000,5893.400000,1316.600000,2140.100000,63650.500000,55200.600000,0.000000,63650.600000
2006,30913.100000,1838.700,9533.200000,7321.600000,1129.900000,11089.700000,31762.700000,1189.600000,16769.000000,1802.600000,...,5370.500000,NaN,21907.100000,8941.900000,1196.900000,439.500000,95070.800000,89700.300000,852.446017,95923.446017
2007,9862.100000,3592.000,165.100000,3751.000000,198.800000,2155.200000,36614.000000,-947.700000,17193.800000,4368.400000,...,11120.000000,NaN,12187.200000,-3444.400000,7531.000000,5386.700000,61242.300000,50122.300000,694.783785,61937.083785
2008,14370.800000,1034.000,5693.100000,698.200000,-264.900000,7210.400000,34235.500000,422.800000,3007.200000,15818.400000,...,5788.500000,NaN,1095.400000,-7993.700000,954.500000,-422.600000,49100.100000,43311.600000,-513.841126,48586.058874
2009,8.200000,-69.000,-3851.000000,1162.000000,1402.700000,1363.500000,8347.500000,8931.200000,-6058.100000,-8957.000000,...,1127.200000,NaN,3309.600000,6373.700000,213.900000,2420.600000,28703.300000,27576.100000,-148.883489,28554.416511
2010,1400.500000,-3157.400,4462.700000,-1089.300000,2655.700000,-1471.200000,27383.900000,6145.700000,13240.200000,120.200000,...,48092.100000,NaN,4535.100000,13306.000000,500.300000,1634.500000,89378.100000,41286.000000,502.494731,89880.594731
2011,-8520.400000,-4491.200,-4833.600000,-7439.400000,2689.100000,5554.700000,12726.200000,6461.600000,-3132.700000,-2423.100000,...,-1215.600000,NaN,1405.200000,11700.500000,539.000000,1545.900000,42754.600000,43970.200000,358.635129,43113.235129
2012,9014.200000,1073.200,2199.300000,1274.300000,1699.900000,2767.600000,23174.300000,4831.100000,7520.600000,6252.400000,...,-7250.100000,NaN,5186.700000,4583.700000,1020.000000,1613.100000,40870.300000,48120.400000,459.623152,41329.923152
2013,-3108.700000,-968.300,-1846.100000,-782.200000,-971.200000,1459.100000,11597.500000,-1859.000000,2346.000000,2137.200000,...,-2768.600000,NaN,13320.300000,4691.200000,780.300000,160.200000,35752.400000,38521.000000,-30.452894,35721.947106
2014,-6511.977010,-541.700,-151.988984,1252.580805,1000.660196,-8071.529027,-27645.577394,-18808.447112,5073.646085,2188.058479,...,10268.099110,-710.189437,-7009.333644,6933.005977,-816.939544,-5517.403718,-165.353450,-10433.452561,215.881831,50.528381
2015,1856.290809,-454.900,3072.031875,-1717.272654,1986.051412,-1029.619825,48917.792593,7353.350341,38288.166363,311.160000,...,39083.287300,12155.954798,-2416.525205,7078.124248,3139.989783,447.955928,90077.985633,50994.698332,280.149600,90358.135233
2016,20677.644098,91.114,1631.599559,1218.177608,10285.139794,7451.613137,-7684.543826,2410.418923,-22882.337389,5057.647139,...,2070.568894,9467.991291,2116.945718,20102.670359,508.517275,5320.476411,70658.685896,68588.117002,766.624563,71425.310459

In [318]:
df['Sektoren']

0     1998
1     1999
2     2000
3     2001
4     2002
5     2003
6     2004
7     2005
8     2006
9     2007
10    2008
11    2009
12    2010
13    2011
14    2012
15    2013
16    2014
17    2015
18    2016
Name: Sektoren, dtype: int64

In [319]:
df['Industrie - Total']

0      6374.000000
1      4606.000000
2     17634.500000
3      8012.800000
4     11437.200000
5      2180.900000
6     11829.500000
7     10192.900000
8     30913.100000
9      9862.100000
10    14370.800000
11        8.200000
12     1400.500000
13    -8520.400000
14     9014.200000
15    -3108.700000
16    -6511.977010
17     1856.290809
18    20677.644098
Name: Industrie - Total, dtype: float64

In [320]:
df.dtypes

Sektoren                                                                                                     int64
Industrie - Total                                                                                          float64
Industrie - Textilien und Bekleidung                                                                       float64
Industrie - Chemie und Kunststoffe                                                                         float64
Industrie - Metalle und Maschinen                                                                          float64
Industrie - Elektronik, Energie, Optik und Uhren                                                           float64
Industrie - Übrige Industrien und Bau                                                                      float64
Dienste - Total                                                                                            float64
Dienste - Handel                                                                                           float64
Dienste - Finanz- und Holdinggesellschaften - Total                                                        float64
Dienste - Finanz- und Holdinggesellschaften - schweizerisch beherrscht                                     float64
Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - Total                               float64
Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - davon Special Purpose Entities      float64
Dienste - Banken                                                                                           float64
Dienste - Versicherungen                                                                                   float64
Dienste - Transporte und Kommunikation                                                                     float64
Dienste - Übrige Dienste                                                                                   float64
Total                                                                                                      float64
Total ohne ausländisch beherrschte Finanz- und Holdinggesellschaften                                       float64
Pro memoria: Grundstücks- und Wohnungswesen                                                                float64
Pro memoria: Total inkl. Grundstücks- und Wohnungswesen                                                    float64
Industrie - Total.1                                                                                        float64
Industrie - Textilien und Bekleidung.1                                                                     float64
Industrie - Chemie und Kunststoffe.1                                                                       float64
Industrie - Metalle und Maschinen.1                                                                        float64
Industrie - Elektronik, Energie, Optik und Uhren.1                                                         float64
Industrie - Übrige Industrien und Bau.1                                                                    float64
Dienste - Total.1                                                                                          float64
Dienste - Handel.1                                                                                         float64
Dienste - Finanz- und Holdinggesellschaften - Total.1                                                      float64
                                                                                                            ...
Dienste - Finanz- und Holdinggesellschaften - Total.2                                                      float64
Dienste - Finanz- und Holdinggesellschaften - schweizerisch beherrscht.2                                   float64
Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - Total.2                             float64
Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - davon Special Purpose Entities.2    float64
Dienste - Banken.2                                                                                         float64
Dienste - Versicherungen.2                                                                                 float64
Dienste - Transporte und Kommunikation.2                                                                   float64
Dienste - Übrige Dienste.2                                                                                 float64
Total.2                                                                                                    float64
Total ohne ausländisch beherrschte Finanz- und Holdinggesellschaften.2                                     float64
Industrie - Total.3                                                                                        float64
Industrie - Textilien und Bekleidung.3                                                                     float64
Industrie - Chemie und Kunststoffe.3                                                                       float64
Industrie - Metalle und Maschinen.3                                                                        float64
Industrie - Elektronik, Energie, Optik und Uhren.3                                                         float64
Industrie - Übrige Industrien und Bau.3                                                                    float64
Dienste - Total.3                                                                                          float64
Dienste - Handel.3                                                                                         float64
Dienste - Finanz- und Holdinggesellschaften - Total.3                                                      float64
Dienste - Finanz- und Holdinggesellschaften - schweizerisch beherrscht.3                                   float64
Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - Total.3                             float64
Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - davon Special Purpose Entities.3    float64
Dienste - Banken.3                                                                                         float64
Dienste - Versicherungen.3                                                                                 float64
Dienste - Transporte und Kommunikation.3                                                                   float64
Dienste - Übrige Dienste.3                                                                                 float64
Total.3                                                                                                    float64
Total ohne ausländisch beherrschte Finanz- und Holdinggesellschaften.3                                     float64
Pro memoria: Grundstücks- und Wohnungswesen.1                                                              float64
Pro memoria: Total inkl. Grundstücks- und Wohnungswesen.1                                                  float64
Length: 77, dtype: object

In [321]:
df["Sektoren"] = df['Sektoren'].astype('int')
df.dtypes

Sektoren                                                                                                     int64
Industrie - Total                                                                                          float64
Industrie - Textilien und Bekleidung                                                                       float64
Industrie - Chemie und Kunststoffe                                                                         float64
Industrie - Metalle und Maschinen                                                                          float64
Industrie - Elektronik, Energie, Optik und Uhren                                                           float64
Industrie - Übrige Industrien und Bau                                                                      float64
Dienste - Total                                                                                            float64
Dienste - Handel                                                                                           float64
Dienste - Finanz- und Holdinggesellschaften - Total                                                        float64
Dienste - Finanz- und Holdinggesellschaften - schweizerisch beherrscht                                     float64
Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - Total                               float64
Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - davon Special Purpose Entities      float64
Dienste - Banken                                                                                           float64
Dienste - Versicherungen                                                                                   float64
Dienste - Transporte und Kommunikation                                                                     float64
Dienste - Übrige Dienste                                                                                   float64
Total                                                                                                      float64
Total ohne ausländisch beherrschte Finanz- und Holdinggesellschaften                                       float64
Pro memoria: Grundstücks- und Wohnungswesen                                                                float64
Pro memoria: Total inkl. Grundstücks- und Wohnungswesen                                                    float64
Industrie - Total.1                                                                                        float64
Industrie - Textilien und Bekleidung.1                                                                     float64
Industrie - Chemie und Kunststoffe.1                                                                       float64
Industrie - Metalle und Maschinen.1                                                                        float64
Industrie - Elektronik, Energie, Optik und Uhren.1                                                         float64
Industrie - Übrige Industrien und Bau.1                                                                    float64
Dienste - Total.1                                                                                          float64
Dienste - Handel.1                                                                                         float64
Dienste - Finanz- und Holdinggesellschaften - Total.1                                                      float64
                                                                                                            ...
Dienste - Finanz- und Holdinggesellschaften - Total.2                                                      float64
Dienste - Finanz- und Holdinggesellschaften - schweizerisch beherrscht.2                                   float64
Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - Total.2                             float64
Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - davon Special Purpose Entities.2    float64
Dienste - Banken.2                                                                                         float64
Dienste - Versicherungen.2                                                                                 float64
Dienste - Transporte und Kommunikation.2                                                                   float64
Dienste - Übrige Dienste.2                                                                                 float64
Total.2                                                                                                    float64
Total ohne ausländisch beherrschte Finanz- und Holdinggesellschaften.2                                     float64
Industrie - Total.3                                                                                        float64
Industrie - Textilien und Bekleidung.3                                                                     float64
Industrie - Chemie und Kunststoffe.3                                                                       float64
Industrie - Metalle und Maschinen.3                                                                        float64
Industrie - Elektronik, Energie, Optik und Uhren.3                                                         float64
Industrie - Übrige Industrien und Bau.3                                                                    float64
Dienste - Total.3                                                                                          float64
Dienste - Handel.3                                                                                         float64
Dienste - Finanz- und Holdinggesellschaften - Total.3                                                      float64
Dienste - Finanz- und Holdinggesellschaften - schweizerisch beherrscht.3                                   float64
Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - Total.3                             float64
Dienste - Finanz- und Holdinggesellschaften - ausländisch beherrscht - davon Special Purpose Entities.3    float64
Dienste - Banken.3                                                                                         float64
Dienste - Versicherungen.3                                                                                 float64
Dienste - Transporte und Kommunikation.3                                                                   float64
Dienste - Übrige Dienste.3                                                                                 float64
Total.3                                                                                                    float64
Total ohne ausländisch beherrschte Finanz- und Holdinggesellschaften.3                                     float64
Pro memoria: Grundstücks- und Wohnungswesen.1                                                              float64
Pro memoria: Total inkl. Grundstücks- und Wohnungswesen.1                                                  float64
Length: 77, dtype: object

In [322]:
df['Beteiligungskapital'] = df.Beteiligungskapital.astype(float)

AttributeError: 'DataFrame' object has no attribute 'Beteiligungskapital'

In [323]:
.astype)(int)

SyntaxError: invalid syntax (<ipython-input-323-b113db00c8d2>, line 1)

In [273]:
df['Beteiligungskapital'].astype(str).astype(int)

ValueError: invalid literal for int() with base 10: 'Industrie - Total'

In [275]:
cdf = df.convert_objects(convert_numeric=True)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.

In [249]:
data = {'Beteiligungskapital'}

df = pd.DataFrame(data, index = ['Kapitalart', 'Selektoren und Branchen','1998', '1999', '2000', '2001', '2001', '2002',
                                 '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
                                 '2012', '2013', '2014', '2015', '2016'])
df

ValueError: DataFrame constructor not properly called!

In [244]:
df.Beteiligungskapital.value_counts().sort_index()

AttributeError: 'DataFrame' object has no attribute 'Beteiligungskapital'

In [211]:
data = {'Beteiligungskapital ohne reinvestierte Erträge': [2]}


df = pd.DataFrame(data, index = ['Kapitalart', 'Selektoren und Branchen','1998', '1999', '2000', '2001', '2001', '2002',
                                 '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
                                 '2012', '2013', '2014', '2015', '2016'])
df





df_irn = df[data]
df_irn.head(3)


df_irn.data.value_counts().sort_index().plot()

TypeError: unhashable type: 'dict'

In [166]:
df.set_index('Jahre')

Empty DataFrame
Columns: []
Index: [Selektoren und Branchen, 1998, 1999, 2000, 2001, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016]

In [ ]:
felderliste = ['Jahre', 'Beteiligungskapital ohne reinvestierte Erträge', 'Beteiligungskapital ohne reinvestierte Erträge.1',
               'Beteiligungskapital ohne reinvestierte Erträge.2', 'Beteiligungskapital ohne reinvestierte Erträge.3']

In [171]:
felderliste = ['Jahre', 'Beteiligungskapital ohne reinvestierte Erträge', 'Beteiligungskapital ohne reinvestierte Erträge.1',
               'Beteiligungskapital ohne reinvestierte Erträge.2', 'Beteiligungskapital ohne reinvestierte Erträge.3']

In [172]:
df[felderliste].head(5)

                     Jahre
0  Selektoren und Branchen
1                     1998
2                     1999
3                     2000
4                     2001

In [ ]:
df = pd.DataFrame({'Kapitalart': ['Selektoren und Branchen','1998', '1999', '2000', '2001', '2001', '2002',
                                 '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
                                 '2012', '2013', '2014', '2015', '2016'],
                   'Beteiligungskapital ohne reinvestierte Erträge': ['6374']})
                  




df.columns = ['Jahre',]
df




data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'year': [2012, 2012, 2013, 2014, 2014], 
        'reports': [4, 24, 31, 2, 3]}
df = pd.DataFrame(data, index = ['Cochice', 'Pima', 'Santa Cruz', 'Maricopa', 'Yuma'])
df

In [139]:
df.drop([1])

,Kapitalart,Beteiligungskapital ohne reinvestierte Erträge,Beteiligungskapital ohne reinvestierte Erträge.1,Beteiligungskapital ohne reinvestierte Erträge.2,Beteiligungskapital ohne reinvestierte Erträge.3,Beteiligungskapital ohne reinvestierte Erträge.4,Beteiligungskapital ohne reinvestierte Erträge.5,Beteiligungskapital ohne reinvestierte Erträge.6,Beteiligungskapital ohne reinvestierte Erträge.7,Beteiligungskapital ohne reinvestierte Erträge.8,...,Total.10,Total.11,Total.12,Total.13,Total.14,Total.15,Total.16,Total.17,Total.18,Total.19
0,Sektoren und Branchen,Industrie - Total,Industrie - Textilien und Bekleidung,Industrie - Chemie und Kunststoffe,Industrie - Metalle und Maschinen,"Industrie - Elektronik, Energie, Optik und Uhren",Industrie - Übrige Industrien und Bau,Dienste - Total,Dienste - Handel,Dienste - Finanz- und Holdinggesellschaften - ...,...,Dienste - Finanz- und Holdinggesellschaften - ...,Dienste - Finanz- und Holdinggesellschaften - ...,Dienste - Banken,Dienste - Versicherungen,Dienste - Transporte und Kommunikation,Dienste - Übrige Dienste,Total,Total ohne ausländisch beherrschte Finanz- und...,Pro memoria: Grundstücks- und Wohnungswesen,Pro memoria: Total inkl. Grundstücks- und Wohn...
2,1998,6374,285.5,3829.8,819.5,108,1331.2,10574.8,369,565.5,...,3869.9,NaN,-321.2,8034.4,859.3,62,27209.2,23339.3,NaN,27209.2
3,1999,4606,440,198.5,650.8,1111.1,2205.6,19229.1,52.8,3778.3,...,11479.6,NaN,6082,9910.2,3524.3,4121.3,49986.2,38506.6,NaN,49986.2
4,2000,17634.5,19,7680.3,1271.6,2062,6601.6,38377.8,109.2,1900.7,...,257.6,NaN,31059.1,14041.6,196.3,2265.6,75445.8,75188.2,NaN,75445.6
5,2001,8012.8,-224.9,2583.7,1707.4,2071.5,1875.1,13982.6,890.9,167.5,...,1884.7,NaN,-793.6,7492.8,1521.1,1528,30916.2,29031.5,NaN,30916.2
6,2002,11437.2,37.3,3444,431.8,232.8,7291.3,13146.4,-90.2,3710.7,...,4535.6,NaN,436.8,-573.2,-1382.8,-1220.4,12785,8249.4,NaN,12785.2
7,2003,2180.9,421.5,-225.3,1327.8,-80.3,737.2,3399.6,39.8,1261.7,...,4696.2,NaN,6176.1,1414.2,-539.7,576.3,20794.5,16098.3,0,20794.8
8,2004,11829.5,791.4,7521.2,2249.5,-100.2,1367.6,-212.8,599.7,-4270.2,...,2245.5,NaN,3225.1,3815.2,-46.8,725.5,32666,30420.5,0,32665.8
9,2005,10192.9,1430.3,6763.7,-585.9,194.6,2390.2,11789.3,1687.6,2208.9,...,8449.9,NaN,8382.7,5893.4,1316.6,2140.1,63650.5,55200.6,0,63650.6
10,2006,30913.1,1838.7,9533.2,7321.6,1129.9,11089.7,31762.7,1189.6,16769,...,5370.5,NaN,21907.1,8941.9,1196.9,439.5,95070.8,89700.3,852.446,95923.4
11,2007,9862.1,3592,165.1,3751,198.8,2155.2,36614,-947.7,17193.8,...,11120,NaN,12187.2,-3444.4,7531,5386.7,61242.3,50122.3,694.784,61937.1
12,2008,14370.8,1034,5693.1,698.2,-264.9,7210.4,34235.5,422.8,3007.2,...,5788.5,NaN,1095.4,-7993.7,954.5,-422.6,49100.1,43311.6,-513.841,48586.1
13,2009,8.2,-69,-3851,1162,1402.7,1363.5,8347.5,8931.2,-6058.1,...,1127.2,NaN,3309.6,6373.7,213.9,2420.6,28703.3,27576.1,-148.883,28554.4
14,2010,1400.5,-3157.4,4462.7,-1089.3,2655.7,-1471.2,27383.9,6145.7,13240.2,...,48092.1,NaN,4535.1,13306,500.3,1634.5,89378.1,41286,502.495,89880.6
15,2011,-8520.4,-4491.2,-4833.6,-7439.4,2689.1,5554.7,12726.2,6461.6,-3132.7,...,-1215.6,NaN,1405.2,11700.5,539,1545.9,42754.6,43970.2,358.635,43113.2
16,2012,9014.2,1073.2,2199.3,1274.3,1699.9,2767.6,23174.3,4831.1,7520.6,...,-7250.1,NaN,5186.7,4583.7,1020,1613.1,40870.3,48120.4,459.623,41329.9
17,2013,-3108.7,-968.3,-1846.1,-782.2,-971.2,1459.1,11597.5,-1859,2346,...,-2768.6,NaN,13320.3,4691.2,780.3,160.2,35752.4,38521,-30.4529,35721.9
18,2014,-6511.98,-541.7,-151.989,1252.58,1000.66,-8071.53,-27645.6,-18808.4,5073.65,...,10268.1,-710.189,-7009.33,6933.01,-816.94,-5517.4,-165.353,-10433.5,215.882,50.5284
19,2015,1856.29,-454.9,3072.03,-1717.27,1986.05,-1029.62,48917.8,7353.35,38288.2,...,39083.3,12156,-2416.53,7078.12,3139.99,447.956,90078,50994.7,280.15,90358.1
20,2016,20677.6,91.114,1631.6,1218.18,10285.1,7451.61,-7684.54,2410.42,-22882.3,...,2070.57,9467.99,2116.95,20102.7,508.517,5320.48,70658.7,68588.1,766.625,71425.3

In [ ]:
df_kapital..value_counts().sort_index().plot()

In [ ]:
df_irn = df[df.Beteiligungskapital ohne reinvestierte Erträge.1 == 'IRN']
df_irn.head(3)

In [129]:
data = {'Beteiligungskapital ohne reinvestierte Erträge': ['']}
df = pd.DataFrame(data, index = ['Kapitalart', 'Sektoren und Branchen', 'Leerzeile',
                                 '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2205',
                                '2006', '2007', '2008', '2009', '2010', '2011', '2012',
                                '2013', '2014', '2015', '2016'])
df

                      Beteiligungskapital ohne reinvestierte Erträge
Kapitalart
Sektoren und Branchen
Leerzeile
1998
1999
2000
2001
2002
2003
2004
2205
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016

In [130]:
df.drop(['Leerzeile'])

                      Beteiligungskapital ohne reinvestierte Erträge
Kapitalart
Sektoren und Branchen
1998
1999
2000
2001
2002
2003
2004
2205
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016

In [98]:
df.shape

(21, 77)

In [ ]:
data = {}
df = pd.DataFrame(data, index = ['Kapitalart', 'Sektoren und Branchen', 'Leerzeile',
                                 '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2205',
                                '2006', '2007', '2008', '2009', '2010', '2011', '2012',
                                '2013', '2014', '2015', '2016'])
df


'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'year': [2012, 2012, 2013, 2014, 2014], 
        'reports': [4, 24, 31, 2, 3]

In [ ]:
data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'year': [2012, 2012, 2013, 2014, 2014], 
        'reports': [4, 24, 31, 2, 3]}

df = pd.DataFrame(data, index = ['Cochice', 'Pima', 'Santa Cruz', 'Maricopa', 'Yuma'])
df

In [90]:
df.dtypes

Kapitalart                                           object
Beteiligungskapital ohne reinvestierte Erträge       object
Beteiligungskapital ohne reinvestierte Erträge.1     object
Beteiligungskapital ohne reinvestierte Erträge.2     object
Beteiligungskapital ohne reinvestierte Erträge.3     object
Beteiligungskapital ohne reinvestierte Erträge.4     object
Beteiligungskapital ohne reinvestierte Erträge.5     object
Beteiligungskapital ohne reinvestierte Erträge.6     object
Beteiligungskapital ohne reinvestierte Erträge.7     object
Beteiligungskapital ohne reinvestierte Erträge.8     object
Beteiligungskapital ohne reinvestierte Erträge.9     object
Beteiligungskapital ohne reinvestierte Erträge.10    object
Beteiligungskapital ohne reinvestierte Erträge.11    object
Beteiligungskapital ohne reinvestierte Erträge.12    object
Beteiligungskapital ohne reinvestierte Erträge.13    object
Beteiligungskapital ohne reinvestierte Erträge.14    object
Beteiligungskapital ohne reinvestierte Erträge.15    object
Beteiligungskapital ohne reinvestierte Erträge.16    object
Beteiligungskapital ohne reinvestierte Erträge.17    object
Beteiligungskapital ohne reinvestierte Erträge.18    object
Beteiligungskapital ohne reinvestierte Erträge.19    object
Reinvestierte Erträge                                object
Reinvestierte Erträge.1                              object
Reinvestierte Erträge.2                              object
Reinvestierte Erträge.3                              object
Reinvestierte Erträge.4                              object
Reinvestierte Erträge.5                              object
Reinvestierte Erträge.6                              object
Reinvestierte Erträge.7                              object
Reinvestierte Erträge.8                              object
                                                      ...
Kredite und Schuldtitel.8                            object
Kredite und Schuldtitel.9                            object
Kredite und Schuldtitel.10                           object
Kredite und Schuldtitel.11                           object
Kredite und Schuldtitel.12                           object
Kredite und Schuldtitel.13                           object
Kredite und Schuldtitel.14                           object
Kredite und Schuldtitel.15                           object
Kredite und Schuldtitel.16                           object
Kredite und Schuldtitel.17                           object
Total                                                object
Total.1                                              object
Total.2                                              object
Total.3                                              object
Total.4                                              object
Total.5                                              object
Total.6                                              object
Total.7                                              object
Total.8                                              object
Total.9                                              object
Total.10                                             object
Total.11                                             object
Total.12                                             object
Total.13                                             object
Total.14                                             object
Total.15                                             object
Total.16                                             object
Total.17                                             object
Total.18                                             object
Total.19                                             object
Length: 77, dtype: object

In [18]:
df.set_index('Kapitalart')

KeyError: 'Kapitalart'

In [12]:
df = df.transpose()

In [13]:
df

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
Kapitalart,Sektoren und Branchen,NaN,1998,1999,2000,2001,2002,2003,2004,2005,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
Beteiligungskapital ohne reinvestierte Erträge,Industrie - Total,"EPB@SNB.fdiaustabsa{D0_0,T0}",6374,4606,17634.5,8012.8,11437.2,2180.9,11829.5,10192.9,...,9862.1,14370.8,8.2,1400.5,-8520.4,9014.2,-3108.7,-6511.98,1856.29,20677.6
Beteiligungskapital ohne reinvestierte Erträge.1,Industrie - Textilien und Bekleidung,"EPB@SNB.fdiaustabsa{D0_0,TUB}",285.5,440,19,-224.9,37.3,421.5,791.4,1430.3,...,3592,1034,-69,-3157.4,-4491.2,1073.2,-968.3,-541.7,-454.9,91.114
Beteiligungskapital ohne reinvestierte Erträge.2,Industrie - Chemie und Kunststoffe,"EPB@SNB.fdiaustabsa{D0_0,CUK}",3829.8,198.5,7680.3,2583.7,3444,-225.3,7521.2,6763.7,...,165.1,5693.1,-3851,4462.7,-4833.6,2199.3,-1846.1,-151.989,3072.03,1631.6
Beteiligungskapital ohne reinvestierte Erträge.3,Industrie - Metalle und Maschinen,"EPB@SNB.fdiaustabsa{D0_0,MUM}",819.5,650.8,1271.6,1707.4,431.8,1327.8,2249.5,-585.9,...,3751,698.2,1162,-1089.3,-7439.4,1274.3,-782.2,1252.58,-1717.27,1218.18
Beteiligungskapital ohne reinvestierte Erträge.4,"Industrie - Elektronik, Energie, Optik und Uhren","EPB@SNB.fdiaustabsa{D0_0,EEOU}",108,1111.1,2062,2071.5,232.8,-80.3,-100.2,194.6,...,198.8,-264.9,1402.7,2655.7,2689.1,1699.9,-971.2,1000.66,1986.05,10285.1
Beteiligungskapital ohne reinvestierte Erträge.5,Industrie - Übrige Industrien und Bau,"EPB@SNB.fdiaustabsa{D0_0,UIB}",1331.2,2205.6,6601.6,1875.1,7291.3,737.2,1367.6,2390.2,...,2155.2,7210.4,1363.5,-1471.2,5554.7,2767.6,1459.1,-8071.53,-1029.62,7451.61
Beteiligungskapital ohne reinvestierte Erträge.6,Dienste - Total,"EPB@SNB.fdiaustabsa{D0_0,T1}",10574.8,19229.1,38377.8,13982.6,13146.4,3399.6,-212.8,11789.3,...,36614,34235.5,8347.5,27383.9,12726.2,23174.3,11597.5,-27645.6,48917.8,-7684.54
Beteiligungskapital ohne reinvestierte Erträge.7,Dienste - Handel,"EPB@SNB.fdiaustabsa{D0_0,H}",369,52.8,109.2,890.9,-90.2,39.8,599.7,1687.6,...,-947.7,422.8,8931.2,6145.7,6461.6,4831.1,-1859,-18808.4,7353.35,2410.42
Beteiligungskapital ohne reinvestierte Erträge.8,Dienste - Finanz- und Holdinggesellschaften - ...,"EPB@SNB.fdiaustabsa{D0_0,T2}",565.5,3778.3,1900.7,167.5,3710.7,1261.7,-4270.2,2208.9,...,17193.8,3007.2,-6058.1,13240.2,-3132.7,7520.6,2346,5073.65,38288.2,-22882.3
Beteiligungskapital ohne reinvestierte Erträge.9,Dienste - Finanz- und Holdinggesellschaften - ...,"EPB@SNB.fdiaustabsa{D0_0,SB}",1133.4,150.3,2002.9,1394.8,2345.2,785.6,-1476,-779.1,...,4368.4,15818.4,-8957,120.2,-2423.1,6252.4,2137.2,2188.06,311.16,5057.65
Beteiligungskapital ohne reinvestierte Erträge.10,Dienste - Finanz- und Holdinggesellschaften - ...,"EPB@SNB.fdiaustabsa{D0_0,T3}",-567.9,3628,-102.2,-1227.3,1365.5,476.1,-2794.2,2988,...,12825.4,-12811.2,2898.9,13120,-709.6,1268.2,208.8,2885.59,37977,-27940
Beteiligungskapital ohne reinvestierte Erträge.11,Dienste - Finanz- und Holdinggesellschaften - ...,"EPB@SNB.fdiaustabsa{D0_0,DSPE}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-277.712,19232,10637.7
Beteiligungskapital ohne reinvestierte Erträge.12,Dienste - Banken,"EPB@SNB.fdiaustabsa{D0_0,B}",2869.2,3936.7,26993.4,1597.2,7931,4433.1,-260.5,4824.9,...,20094.3,36738.2,469.6,2627,2093,8819.1,13582.2,-8889.31,-293.498,4375.43
Beteiligungskapital ohne reinvestierte Erträge.13,Dienste - Versicherungen,"EPB@SNB.fdiaustabsa{D0_0,V}",6227.4,5792.6,7181.5,7531.7,2100.5,-2049.5,1011.5,666.3,...,-7677.3,-6107,704.5,5353.4,4914.3,823.9,-2763.7,1304.56,1079.6,5042.39
Beteiligungskapital ohne reinvestierte Erträge.14,Dienste - Transporte und Kommunikation,"EPB@SNB.fdiaustabsa{D0_0,TUK}",742.4,3581.5,1224.5,863.3,35,-395.9,-61.6,1039.3,...,4594.4,517.8,-39.5,377.8,1808.6,845.3,48.3,116.88,2158.61,-213.353
Beteiligungskapital ohne reinvestierte Erträge.15,Dienste - Übrige Dienste,"EPB@SNB.fdiaustabsa{D0_0,DU}",-198.7,2087.2,968.5,2932,-540.6,110.4,2768.3,1362.3,...,3356.5,-343.5,4339.8,-360.3,581.4,334.2,243.7,-6442.91,331.565,3582.91
Beteiligungskapital ohne reinvestierte Erträge.16,Total,"EPB@SNB.fdiaustabsa{D0_0,D1_2}",16948.8,23835.1,56012.3,21995.4,24583.6,5580.5,11616.7,21982.2,...,46476,48606.3,8355.7,28784.4,4205.8,32188.5,8488.8,-34157.6,50774.1,12993.1
Beteiligungskapital ohne reinvestierte Erträge.17,Total ohne ausländisch beherrschte Finanz- und...,"EPB@SNB.fdiaustabsa{D0_0,D1_3}",17516.7,20207.1,56114.5,23222.7,23218.1,5104.4,14410.9,18994.2,...,33650.6,61417.5,5456.8,15664.4,4915.4,30920.3,8280,-37043.1,12797.1,40933.1
Beteiligungskapital ohne reinvestierte Erträge.18,Pro memoria: Grundstücks- und Wohnungswesen,"EPB@SNB.fdiaustabsa{D0_0,PMG}",NaN,NaN,NaN,NaN,NaN,0,0,0,...,694.784,-513.841,-148.883,502.495,358.635,459.623,-30.4529,215.882,280.15,766.625
Beteiligungskapital ohne reinvestierte Erträge.19,Pro memoria: Total inkl. Grundstücks- und Wohn...,"EPB@SNB.fdiaustabsa{D0_0,PMT}",16948.8,23835.1,56012.3,21995.4,24583.6,5580.5,11616.7,21982.2,...,47170.8,48092.5,8206.82,29286.9,4564.44,32648.1,8458.35,-33941.7,51054.2,13759.7
Reinvestierte Erträge,Industrie - Total,"EPB@SNB.fdiaustabsa{D0_1,T0}",1045.4,3892.2,7005.6,2006.7,-233.3,6086.9,7596.8,16568.3,...,14566.5,9417.4,15502.4,16676.6,9314.9,11255.1,4011.5,22500.9,20944.5,10876.8
Reinvestierte Erträge.1,Industrie - Textilien und Bekleidung,"EPB@SNB.fdiaustabsa{D0_1,TUB}",56.2,-24.2,-104.4,-55.3,114.4,88.8,-163.7,1142.3,...,1082.7,-927.6,-390.7,-223,-376.9,-189.9,-326.1,-294.161,922.98,-997.871
Reinvestierte Erträge.2,Industrie - Chemie und Kunststoffe,"EPB@SNB.fdiaustabsa{D0_1,CUK}",-757.6,3240.9,5590.2,-1373,-606.8,3855.2,4184.8,9660.7,...,7432.8,2958.9,7998.7,3216.6,2371.6,5742.1,4237.8,7656.46,9949.91,5992.69
Reinvestierte Erträge.3,Industrie - Metalle und Maschinen,"EPB@SNB.fdiaustabsa{D0_1,MUM}",1086,-465,165.8,420.8,-1542.7,241.4,41.7,1570.3,...,1496.5,576.7,-236.8,1000,660.4,932,-638.9,728.415,1058.63,2232.23
Reinvestierte Erträge.4,"Industrie - Elektronik, Energie, Optik und Uhren","EPB@SNB.fdiaustabsa{D0_1,EEOU}",0,188.7,335.1,-155.4,1506,-1095.4,-766,-336,...,1077.9,3436,3394.2,5809.4,3539.2,1448.6,1401.5,5335.91,4601.94,140.363
Reinvestierte Erträge.5,Industrie - Übrige Industrien und Bau,"EPB@SNB.fdiaustabsa{D0_1,UIB}",660.8,951.8,1018.9,3169.6,295.8,2996.9,4300,4531,...,3476.6,3373.5,4736.9,6873.6,3120.6,3322.3,-662.8,9074.31,4411.08,3509.35
Reinvestierte Erträge.6,Dienste - Total,"EPB@SNB.fdiaustabsa{D0_1,T1}",6157.4,14387.3,9831.6,2125.6,-7907,10033.7,13570.9,24448.9,...,-8316.3,-35278.5,12131.2,19437.7,-1402.1,5010.4,4194.3,8305.28,8445.59,14503.8
Reinvestierte Erträge.7,Dienste - Handel,"EPB@SNB.fdiaustabsa{D0_1,H}",728.6,728,81.9,778,1167,1344.1,876.3,1011.2,...,736.5,2051.7,1320.7,3155.7,1525.5,815.8,-2111.7,3585.56,1101.42,5399.69
Reinvestierte Erträge.8,Dienste - Finanz- und Holdinggesellschaften - ...,"EPB@SNB.fdiaustabsa{D0_1,T2}",6763.9,7170.9,158.5,4324.8,2929.8,3598.9,5603,13722.1,...,-7397,-1378.3,2418.6,5845.3,-8640.4,2703.9,-4358.5,-790.618,5782.44,5757.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kredite und Schuldtitel.8,Dienste - Finanz- und Holdinggesellschaften - ...,"EPB@SNB.fdiaustabsa{D0_2,T2}",-770.5,3117.3,2753.9,4202,-4005.6,2498.7,606.9,-5487.9,...,2982.2,19071.7,-2086.5,29971.3,8841.9,-3358.7,3977.8,752.029,412.785,25932.8
Kredite und Schuldtitel.9,Dienste - Finanz- und Holdinggesellschaften - ...,"EPB@SNB.fdiaustabsa{D0_2,SB}",-273.8,578.4,3456.2,1817.4,-6172.3,1279,999.9,2785.1,...,-3859.1,-1155.1,88.1,285.1,8654.3,7504.7,8606.8,1623.81,-267.305,-261.069
Kredite und Schuldtitel.10,Dienste - Finanz- und Holdinggesellschaften - ...,"EPB@SNB.fdiaustabsa{D0_2,T3}",-496.7,2538.9,-702.3,2384.6,2166.7,1219.7,-393,-8273,...,6841.3,20226.8,-2174.6,29686.2,187.6,-10863.4,-4629,-871.776,680.09,26193.9
Kredite und Schuldtitel.11,Dienste - Finanz- und Holdinggesellschaften - ...,"EPB@SNB.fdiaustabsa{D0_2,DSPE}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2986.42,-274.994
Kredite und Schuldtitel.12,Dienste - Banken,"EPB@SNB.fdiaustabsa{D0_2,B}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kredite und Schuldtitel.13,Dienste - Versicherungen,"EPB@SNB.fdiaustabsa{D0_2,V}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1879.89,2533.61,10994.5
Kredite und Schuldtitel.14,Dienste - Transporte und Kommunikation,"EPB@SNB.fdiaustabsa{D0_2,TUK}",361.8,-71.3,-189.2,584.1,-247.8,49.1,-125.2,-100.1,...,1948.9,-370.9,-129.6,394.3,16.9,132.8,304.3,-61.7495,241.974,337.103
Kredite und Schuldtitel.15,Dienste - Übrige Dienste,"EPB@SNB.fdiaustabsa{D0_2,DU}",-32.5,1822.7,1792.6,-782.8,-13.8,388.9,-2705,224.5,...,999.5,-848.9,-1418.9,1147.1,63.7,-42.5,-3127.2,171.628,635.948,582.72
Kredite und Schuldtitel.16,Total,"EPB@SNB.fdiaustabsa{D0_2,D1_2}",3057.6,7871.6,2596.1,4788.5,-3658.1,-906.3,-118.6,651.2,...,8516.1,26354.7,-7286,24479.4,30636,-7583.7,19057.7,3185.98,9913.79,32285.1
Kredite und Schuldtitel.17,Total ohne ausländisch beherrschte Finanz- und...,"EPB@SNB.fdiaustabsa{D0_2,D1_3}",3554.3,5332.7,3298.4,2403.9,-5824.8,-2126,274.4,8924.2,...,1674.8,6127.9,-5111.4,-5206.8,30448.4,3279.7,23686.7,4057.75,9233.7,6091.17
Total,Industrie - Total,"EPB@SNB.fdiaustabsa{D0_3,T0}",9640.2,9477.1,23726.2,11393.3,12502,6425.2,21620.3,27214.2,...,27183.6,28320.4,10494.6,7282.8,22681.1,18337.3,10625.8,26065.1,12826.4,28862.9
Total.1,Industrie - Textilien und Bekleidung,"EPB@SNB.fdiaustabsa{D0_3,TUB}",623.1,395.3,-90.1,-278.8,157.1,813.2,-55.5,-1682.9,...,4655.7,37.5,-3145.3,-7134,115.1,-1784.7,1114.9,-2767.06,567.66,1699.22
Total.2,Industrie - Chemie und Kunststoffe,"EPB@SNB.fdiaustabsa{D0_3,CUK}",5156.1,6429.7,17694.6,1498.8,2939,3237.5,11893,20221.2,...,9794.7,6022.2,1632,-1855,15880.6,9385.7,3289,15244.8,866.282,8028.83
Total.3,Industrie - Metalle und Maschinen,"EPB@SNB.fdiaustabsa{D0_3,MUM}",1421.1,659.4,172.5,4797.2,-342.8,1432.8,2053.1,797.7,...,5079.2,4186.4,373.9,-248.3,-8069.3,3426.8,1179.8,3243.8,-249.671,3319.75
Total.4,"Industrie - Elektronik, Energie, Optik und Uhren","EPB@SNB.fdiaustabsa{D0_3,EEOU}",-889.5,1006.8,2394.7,1787.7,681.3,-3246.8,835.9,1048.2,...,677.3,9052.7,6384,9364.2,5082.3,3108,4883.4,5824.63,-955.194,8846.09
Total.5,Industrie - Übrige Industrien und Bau,"EPB@SNB.fdiaustabsa{D0_3,UIB}",3329.4,985.9,3554.5,3588.4,9067.4,4188.5,6893.8,6830,...,6976.7,9021.6,5250,7155.9,9672.4,4201.4,158.7,4518.91,12597.3,6969.02
Total.6,Dienste - Total,"EPB@SNB.fdiaustabsa{D0_3,T1}",17569,40509.1,51719.6,19522.9,283,14369.3,11045.7,36436.3,...,34058.7,20779.7,18208.7,82095.2,20073.5,22533.1,25126.6,-26230.6,77251.6,41795.8
Total.7,Dienste - Handel,"EPB@SNB.fdiaustabsa{D0_3,H}",2375.6,2804.8,-656.1,1080.3,387.7,-616.9,1386.9,8260.4,...,-380.7,6445.4,11616.9,13062.4,7814,3263.7,4209.1,-24855.1,24518.7,4939.48
Total.8,Dienste - Finanz- und Holdinggesellschaften - ...,"EPB@SNB.fdiaustabsa{D0_3,T2}",6558.9,14066.5,4813.1,8694.3,2634.9,7359.3,1939.8,10443.1,...,12778.9,20700.6,-5726,49056.8,-2931.1,6865.9,1965.3,5035.06,44483.4,8807.69
Total.9,Dienste - Finanz- und Holdinggesellschaften - ...,"EPB@SNB.fdiaustabsa{D0_3,SB}",2689,2586.9,4555.5,6809.6,-1900.7,2663.1,-305.7,1993.2,...,1658.9,14912.1,-6853.2,964.7,-1715.5,14116,4733.9,-5233.04,5400.1,6737.12
Total.10,Dienste - Finanz- und Holdinggesellschaften - ...,"EPB@SNB.fdiaustabsa{D0_3,T3}",3869.9,11479.6,257.6,1884.7,4535.6,4696.2,2245.5,8449.9,...,11120,5788.5,1127.2,48092.1,-1215.6,-7250.1,-2768.6,10268.1,39083.3,2070.57
Total.11,Dienste - Finanz- und Holdinggesellschaften - ...,"EPB@SNB.fdiaustabsa{D0_3,DSPE}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-710.189,12156,9467.99
Total.12,Dienste - Banken,"EPB@SNB.fdiaustabsa{D0_3,B}",-321.2,6082,31059.1,-793.6,436.8,6176.1,3225.1,8382.7,...,12187.2,1095.4,3309.6,4535.1,1405.2,5186.7,13320.3,-7009.33,-2416.53,2116.95
Total.13,Dienste - Versicherungen,"EPB@SNB.fdiaustabsa{D0_3,V}",8034.4,9910.2,14041.6,7492.8,-573.2,1414.2,3815.2,5893.4,...,-3444.4,-7993.7,6373.7,13306,11700.5,4583.7,4691.2,6933.01,7078.12,20102.7
Total.14,Dienste - Transporte und Kommunikation,"EPB@SNB.fdiaustabsa{D0_3,TUK}",859.3,3524.3,196.3,1521.1,-1382.8,-539.7,-46.8,1316.6,...,7531,954.5,213.9,500.3,539,1020,780.3,-816.94,3139.99,508.517
Total.15,Dienste - Übrige Dienste,"EPB@SNB.fdiaustabsa{D0_3,DU}",62,4121.3,2265.6,1528,-1220.4,576.3,725.5,2140.1,...,5386.7,-422.6,2420.6,1634.5,1545.9,1613.1,160.2,-5517.4,447.956,5320.48
Total.16,Total,"EPB@SNB.fdiaustabsa{D0_3,D1_2}",27209.2,49986.2,75445.8,30916.2,12785,20794.5,32666,63650.5,...,61242.3,49100.1,28703.3,89378.1,42754.6,40870.3,35752.4,-165.353,90078,70658.7
Total.17,Total ohne ausländisch beherrschte Finanz- und...,"EPB@SNB.fdiaustabsa{D0_3,D1_3}",23339.3,38506.6,75188.2,29031.5,8249.4,16098.3,30420.5,55200.6,...,50122.3,43311.6,27576.1,41286,43970.2,48120.4,38521,-10433.5,50994.7,68588.1
Total.18,Pro memoria: Grundstücks- und Wohnungswesen,"EPB@SNB.fdiaustabsa{D0_3,PMG}",NaN,NaN,NaN,NaN,NaN,0,0,0,...,694.784,-513.841,-148.883,502.495,358.635,459.623,-30.4529,215.882,280.15,766.625
Total.19,Pro memoria: Total inkl. Grundstücks- und Wohn...,"EPB@SNB.fdiaustabsa{D0_3,PMT}",27209.2,49986.2,75445.6,30916.2,12785.2,20794.8,32665.8,63650.6,...,61937.1,48586.1,28554.4,89880.6,43113.2,41329.9,35721.9,50.5284,90358.1,71425.3

In [17]:
df.set_index('Kapitalart')

KeyError: 'Kapitalart'

In [44]:
data = ()

In [45]:
# setting first name as index column 
data.set_index(["Kapitalart"], inplace = True, 
                    append = True, drop = True)

AttributeError: 'tuple' object has no attribute 'set_index'

In [ ]:
df.set_index(['1998', '1999', '2000', '2001',
              '2002', '2003', '2004', '2005', '2006',
              '2007', '2008', '2009', '2010'])