In [4]:
import pandas as pd
import numpy as np

In [5]:
%matplotlib inline

In [6]:
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_excel('2015_Bundesrat.xlsx', index_col=0, header=0)
# df = pd.read_excel('000_snb-di_ohne_reinvestierte.xlsx')

In [11]:
df.fillna(0)

,Unnamed: 1,Departement,F900,BD,XL,SK,eingemietet,Total Flugzeuge,Unnamed: 9,E6,SP,SC,Total Helikopter,BR / Dep.
Name,,,,,,,,,,,,,,
BR,E11,Bundesrat,0,0,0,0,0,0,0.0,0,0,0,0,0
Leer,E11L,Leerflüge alle,18:35:00.038000,0,12:56:00.010000,0,0,31:31:00,0.0,00:51:59.990000,01:23:59.971000,00:42:00.029000,02:57:59.990000,34:29:00
Leer 2,E11P,Leerflüge Pos,12:02:00.010000,0,02:08:00.010000,0,0,14:10:00.019000,0.0,04:27:00.029000,0,00:13:59.981000,04:41:00.010000,18:51:00.029000
Burkhalter Didier,E11A,EDA,180:13:00,0,20:15:00,0,0,200:28:00,0.0,10:07:59.981000,03:54:59.962000,06:38:59.971000,20:42:00,221:10:00
Widmer-Schlumpf Eveline,E11F,EFD,07:12:00,0,03:45:00,0,0,10:57:00,0.0,0,01:54:59.990000,01:18:59.990000,03:13:59.981000,14:10:59.981000
Berset Alain,E11I,EDI,06:36:59.962000,0,06:00:00,0,01:38:00.038000,14:15:00,0.0,26:08:00,01:54:00.029000,12:40:00.019000,40:42:00,54:57:00
Sommaruga Simonetta,E11J,EJPD,50:15:00,0,26:10:00,0,0,76:25:00,0.0,10:36:00.029000,04:21:00,09:53:00.038000,24:50:00,101:15:00
Leuthard Doris,E11U,"UVEK, E11U",27:33:00,0,06:29:59.971000,01:05:59.971000,0,35:09:00,0.0,12:27:59.962000,01:27:00.029000,0,13:54:59.990000,49:04:00
Maurer Ueli,E11V,VBS,38:47:00,0,02:01:00.019000,0,0,40:48:00,0.0,02:05:00.038000,0,0,02:05:00.038000,42:53:00
Schneider-Ammann Johann,E11W,WBF,60:39:00,01:52:59.981000,03:20:00.010000,0,02:19:59.981000,68:12:00,0.0,64:10:00,01:00:00.029000,10:05:00.010000,75:15:00,143:27:00
NaN,TOTAL,Bundesrat,0,0,0,0,0,491:55:00,0.0,0,0,0,188:22:00,680:17:00

In [12]:
df.columns

Index(['Unnamed: 1', 'Departement', 'F900', 'BD', 'XL', 'SK', 'eingemietet',
       'Total Flugzeuge', 'Unnamed: 9', 'E6', 'SP', 'SC', 'Total Helikopter',
       'BR / Dep.'],
      dtype='object')

In [14]:
df.shape

(11, 14)

In [18]:
df_ohnere_total = df[['Total Flugzeuge',
       'Total Helikopter']]

df_ohnere_total.iloc[3:10]
#.plot(
#     kind='bar', figsize=(15,10),
#     fontsize=14,
#     title="DI: Beteiligungskapital ohne reinvestierte Erträge – Total")

                        Total Flugzeuge Total Helikopter
Name
Burkhalter Didier             200:28:00         20:42:00
Widmer-Schlumpf Eveline        10:57:00  03:13:59.981000
Berset Alain                   14:15:00         40:42:00
Sommaruga Simonetta            76:25:00         24:50:00
Leuthard Doris                 35:09:00  13:54:59.990000
Maurer Ueli                    40:48:00  02:05:00.038000
Schneider-Ammann Johann        68:12:00         75:15:00

In [ ]:
# df_ohnere_total = df[['Industrie - Total', 'Dienste - Total', 'Total',
#        'Total ohne ausländisch beherrschte Finanz- und Holdinggesellschaften',
#        #'Pro memoria: Grundstücks- und Wohnungswesen',
#        #'Pro memoria: Total inkl. Grundstücks- und Wohnungswesen'
#         ]]
# df_ohnere_total.iloc[8:19].apply(lambda x: x/1000).plot(
#     kind='bar', figsize=(15,10),
#     fontsize=14,
#     title="DI: Beteiligungskapital ohne reinvestierte Erträge – Total")